apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: renovate
    newName: renovate/renovate
    newTag: 43.0.6

resources:
- sealed-secret.yaml
- config-map.yaml
- cron-job.yaml
- pvc.yaml
